### ISSUE TITLE
Reason for `do { ... } while(0)` in macros?

### ISSUE THREAD

**Issue by aromanro** [benhoyt/protothreads-cpp#9]
I've seen that in the C version they are without this: https://dunkels.com/adam/pt/expansion.html
Is there a reason for the existence of `do { ... } while(0)` in the macros?

I quicky changed them in simcpp and at least the examples seem to work the same.

**Comment by aromanro** [comment]
Probably it's for more complex cases (loops where {} are missing).
I think I'll be using c++ coroutines instead of this, it's a way too nasty hack for my taste.

**Comment by benhoyt** [comment]
Thanks. Yeah, this is a very common pattern in C macros. See https://stackoverflow.com/a/2687595/68707
